title = "Multilib"

[[classOrder]]
section = "Shared"
classes = ["Instance Package","Logger Package","Math Package","Parallel Package","Shared Player Package","String Package","Table Package","Tweener Class","SimpleSpring Class","ReasonTo Class","Raycaster Class","Observer Class","NumberComputer Class","DampedSpring Class","Animator Class"]


[[classOrder]]
section = "MultiUI"
classes = ["ArrowChange","CheckBox","DropDownMenu","DropDownOption","Form","InputField","RadioButton","RadioGroup","Slider"]
