title = "Multilib"

[[classOrder]]
section = "Shared"
classes = ["Instance Package","Logger Package","Math Package","Parallel Package","Shared Player Package","String Package","Table Package"]


[[classOrder]]
section = "MultiUI"
classes = ["ArrowChange","CheckBox","DropDownMenu","DropDownOption","Form","InputField","RadioButton","RadioGroup","Slider"]
