[package]
name = "opkvysxct/multilib"
version = "2.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A Roblox library that allows you to perform simple task even simplier"

exclude = ["build","client","server","moonwave.toml","aftman.toml","wally.toml","README.md"]

[dependencies]
