[package]
name = "opkvysxct/multilib"
version = "2.0.8"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "A Roblox library that allows you to perform simple task even simplier"

[dependencies]
